config/routes.rb
Bookshelf::Application.routes.draw do
  root to: 'reviews#index'

  resources :reviews
  resources :books, only: [:update]
  
  get '/feed' => 'reviews#feed', as: :feed, defaults: { format: 'atom' }
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  def to_s
    name
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  has_many :reviews, dependent: :destroy

  attr_accessor :author_name

  validates :author_id, presence: true
  validates :title, presence: true, uniqueness: { scope: :author }

  before_validation :assign_author

  mount_uploader :cover, CoverUploader

  def to_s
    title
  end

  def rating
    reviews.sum(:rating) / reviews.count.to_f
  end

  private

  def assign_author
    self.author = Author.find_or_create_by_name(author_name) if @author_name.present?
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book

  attr_accessor :author_name, :book_title

  validates :book_id, presence: true
  validates :rating, presence: true, numericality: { in: 1..5 }

  scope :comments, -> { where("COALESCE(body, '') != ''") }

  before_validation :assign_book

  def author_name
    @author_name || book.author.name
  end

  def book_title
    @book_title || book.title
  end

  private

  def assign_book
    self.book = if @book_title.present?
      Book.find_or_create_by_title(book_title) do |book|
        book.author_name = self.author_name
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def update
    @book = Book.find(params[:id])
    @book.update_attributes(book_params)

    redirect_to :back
  end

  private

  def book_params
    params.require(:book).permit(:cover, :remove_cover)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  helper_method :review, :reviews

  def index
    
  end

  def show
    
  end

  def new
    @review = Review.new(author_name: "", book_title: "")
  end

  def create
    @review = Review.create(review_params)

    respond_to do |format|
      if @review.errors.any?
        format.html { render :new }
      else
        format.html { redirect_to action: :index }
      end
    end
  end

  def edit
    
  end

  def update
    review.update_attributes(review_params)

    respond_to do |format|
      if @review.errors.any?
        format.html { render :edit }
      else
        format.html { redirect_to action: :show }
      end
    end
  end

  def destroy
    review.destroy
  end

  def feed
    @reviews = reviews.comments.order("created_at DESC")
    @updated = reviews.first.updated_at unless reviews.empty?

    respond_to do |format|
      format.atom { render layout: false }
      format.rss { redirect_to feed_path(format: :atom), status: :moved_permanently }
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body, :author_name, :book_title)
  end

  def review
    @review ||= Review.find(params[:id])
  end

  def reviews
    @reviews ||= Review.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_book_title(title)
    "«#{title}»"
  end

  def book_title_with_author(book)
    "#{book.author.name} #{format_book_title(book.title)}"
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def snippet(review, size = 400)
    "#{review.body[0...size]}…"
  end
end

app/views/application/index.html.haml
%h1 Hello

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title
      = content_for?(:title) ? yield(:title) : "Книжная полка"
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = auto_discovery_link_tag :atom, feed_path
    = auto_discovery_link_tag :rss, feed_path(format: 'rss')
    = csrf_meta_tags

  %body
    #content.container-fluid
      = yield
    .push

  %footer
    #footer
      .container
        .muted.credit
          2013. Powered by Guinness
          %sup> ®

app/views/reviews/_form.html.haml
= simple_form_for review do |f|
  .row-fluid
    .span12
      = f.error_notification

  .row-fluid
    .span3
      = f.input :author_name, label: false, placeholder: "Автор", input_html: { style: "width: 100%" }
      = f.input :book_title, label: false, placeholder: "Название", input_html: { style: "width: 100%" }
      = f.input :rating, collection: ['Отвратительно', 'Плохо', 'Можно не читать', 'Стоит прочесть', 'Отлично'].map.with_index(1).to_a.reverse

    .span7.offset1
      = f.input :body, label: false, placeholder: "Тут можно написать свое мнение о книге", input_html: { style: "width: 100%; height: 300px" }

  .row-fluid
    .span11.actions.text-right
      = f.button :submit, "Сохранить", class: "btn btn-primary"
      = link_to "Назад", root_path, class: "btn btn-link"

app/views/reviews/edit.html.haml
= render "form"

app/views/reviews/index.html.haml
.page-header
  %h1 Рецензии

.row-fluid
  %ul#reviews.thumbnails
    - reviews.comments.each do |review|
      %li.span4
        .thumbnail
          %h3= book_title_with_author(review.book)
          %p.text-justify
            = image_tag review.book.cover.thumb.url, class: "img-polaroid"
            = snippet(review)
          %p.text-right
            %small= link_to "Читать дальше", review_path(review)
.row-fluid
  %p
    %small
      = link_to "Добавить рецензию", new_review_path

app/views/reviews/new.html.haml
.page-header
  %h1 Новая рецензия

= render "form"

app/views/reviews/show.html.haml
- content_for :title, book_title_with_author(review.book)
.page-header
  %h1
    = book_title_with_author(review.book)

.row-fluid
  .span3
    %p
      = simple_form_for review.book, html: { multipart: true } do |f|
        = image_tag review.book.cover.url, alt: book_title_with_author(review.book)
        = f.input :cover, label: false
        - if review.book.cover.present?
          %label.checkbox
            = f.input :remove_cover, as: :boolean, label: false
            Удалить обложку
    %p
      %strong Оценка:
      = review.rating
    %p
      %small= link_to "Назад к списку рецензий", root_path
  .span9
    = simple_format review.body
.row-fluid
  .span6.offset3
    %p.muted
      %em
        Опубликовано
        = l review.created_at, format: :short
  .span3
    %p.text-right.muted
      %small
        = link_to "Редактировать", edit_review_path(review)
        или
        = link_to "удалить", reviews_path(review), method: :delete, confirm: "Точно?"
        ?